### ISSUE TITLE
question about velocity update order

### ISSUE THREAD

**Issue by weixuef** [pmocz/navier-stokes-spectral-python#1]
Hello, this is a very good project. I have a confusion: before the diffusion term is time discretized (lines 127 to 128 in the program), the velocity has been updated (lines 114, 115, 123, and 124). The diffusion term (lines 127 and 128) uses the updated velocity, whereas I think it should use the velocity before the update. Please help me answer it. Thank you so much!

**Comment by pmocz** [comment]
Both are valid approaches. I did a simple operator splitting here. I think your suggested approach and mine would both formally be 1st order accurate in time, and you'd need to do something more to get 2nd order accuracy
